// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClickableRowController from "./clickable_row_controller"
application.register("clickable-row", ClickableRowController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import FullscreenController from "./fullscreen_controller"
application.register("fullscreen", FullscreenController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
