// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AssessmentTitleController from "./assessment_title_controller"
application.register("assessment-title", AssessmentTitleController)

import ClickableRowController from "./clickable_row_controller"
application.register("clickable-row", ClickableRowController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import FullscreenController from "./fullscreen_controller"
application.register("fullscreen", FullscreenController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NewAssessmentController from "./new_assessment_controller"
application.register("new-assessment", NewAssessmentController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import TabCloserController from "./tab_closer_controller"
application.register("tab-closer", TabCloserController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
