AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.0

# Disable the Style/Documentation cop
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
Style/FormatStringToken:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
