default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: proctor_development
  host: localhost
  username: postgres
  password: postgres
  port: 5432

test:
  <<: *default
  database: proctor_test
  host: localhost
  username: postgres
  password: postgres
  port: 5432

production:
  <<: *default
  database: proctor_production
  username: proctor
  password: <%= ENV["PROCTOR_DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
